name: OpenData Workflow for FAIR Data
on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]'
  #workflow_dispatch:

jobs:
  build:
    uses: robert-koch-institut/OpenData-Workflows/.github/workflows/OpenData_Workflows.yml@main
    with:
      # General Variables 
      ZENODOJSON_PATH: Metadaten/zenodo.json
    
      # Push to OpenCoDE
      OPENCODE_ACTIVE: true
      OPENCODE_GROUPID: 2781
      OPENCODE_ACCESS_USER: RKIOpenData
      
      # Push to GovData Repositoy
      GOVDATA_ACTIVE: false
      GOVDATA_DESTINATION_REPO: robert-koch-institut/Metadaten_fuer_GovData
      
      # Push to NFDI4Health
      NFDI4HEALTH_ACTIVE: false
      
      #Build Open Data Website -> no, use other Github Action to deploy interactive report
      WEBSITE_ACTIVE: false

      #Update Github Details
      GITHUB_DETAILS_ACTIVE: true
          
      
    secrets:
      
      # Token from OpenCoDE Account
      OPENCODE_TOKEN: ${{secrets.OPENCODE_TOKEN}}
    
      # Github Token
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GITHUB_METADATA_TOKEN: ${{secrets.ADMINISTRATION_TOKEN}}
